name: Check xcode completeness

on:
  push:
    paths:
    - '.github/workflows/xcode_check.yml'
    - 'source/**'
    - 'tests/check_xcode.sh'
  pull_request:
    paths:
    - '.github/workflows/xcode_check.yml'
    - 'source/**'
    - 'tests/check_xcode.sh'

jobs:
  check-xcode-completeness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools python3-wheel
        sudo pip3 install docopt openstep_parser
        pip3 install pbxproj --user
    - name: Execute xcode completeness check
      run: |
        ./tests/check_xcode.sh
